#########################################################################################################
##  ####     #      ####  #   #    ####   ####   ######     #     #####  ######     #     #### #######  #
##  #       # #     #      # #     #   #  #   #  #    #    # #    #    # #         # #    #       #     #
##  ####   #####    ####    #      ####   ####   #    #   #####   #    # #        #####   ####    #     #
##  #     #     #      #    #      #   #  #  ##  #    #  #     #  #    # #       #     #     #    #     #
##  #### #       #  ####    #      ####   #    # ###### #       # #####  ###### #       # ####    #     #
#########################################################################################################

editableByCommand: #in ticks, 20 ticks = 1 second
  fadeIn: 20  #sets the time the message needs to fade in
  stay: 40    #sets the time the message stays for
  fadeOut: 20 #sets the time the message needs to fade out
  subtitleMessage: "[BROADCAST]"